library(tidyverse)
library(broom)
library(tictoc)
library(paletteer)
library(glue)
library(furrr)
library(here)
library(splines)
library(nnet)
library(Hmisc)
library(mc2d)
library(mice)
library(lcmm)
library(mice)
library(miceadds)
library(gallimaufr)
library(flextable)
library(officer)
library(beepr)

rm(list = ls())

# 1. Load Data ----
load(here("Data", "df_analysis.Rdata"))
load(here("Data", "mod_probs.Rdata"))
load(here("Data", "lcmm.Rdata"))
